baseURL = "https://kenwoo.me/"
title = "kenwoo.me"

theme = "cocoa-eh"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Kenny Woo"
disqusshortname = ""
pluralizelisttitles = false
googleAnalytics = "UA-112764492-1"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Bridging the mind and body."
#copyright = "Copyright © 2018 Kenny Woo"
logofile = ""
faviconfile = "img/gouki-favicon.jpg"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "wooken"
email = "kenny@kenwoo.me"
linkedin = "wookenny"
twitter = "kenzorz"
social_banner = ""
posts_navigation = true
small_banner_logo = true
latestpostcount = 5 # posts to show on home page
