baseURL = "https://kenwoo.me/"
title = "kenwoo.me"
languageCode = "en-US"

theme = "hugo-PaperMod"

builddrafts = false
author = "Kenny Woo"
googleAnalytics = "UA-112764492-1"

[params]
defaultTheme = "dark"
disableThemeToggle = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "Kenny Woo"
imageUrl = "img/gouki-favicon.jpg"
imageWidth = 120
imageHeight = 120

[[params.socialIcons]]
name = "email"
url = "mailto:kenny@kenwoo.me"

[[params.socialIcons]]
name = "github"
url = "https://github.com/wooken"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/wookenny/"

[[menu.main]]
identifier = "code"
name = "code"
url = "/code"
weight = 10

[params.assets]
favicon = "img/favicon.ico"
favicon16x16 = "img/favicon-16x16.png"
favicon32x32 = "img/favicon-32x32.png"
apple_touch_icon = "img/apple-touch-icon.png"
safari_pinned_tab = "img/safari-pinned-tab.svg"
